[package]
name = "mold"
version = "0.1.0"
authors = ["Thing <thing@mold.world>"]

[dependencies]
#time = "0.1.37"
#regex = "0.2.2"
#find_folder = "0.3.0"
amethyst = { git = "https://github.com/amethyst/amethyst", branch = "develop" }

world = { path = "world" }

[workspace]
members = ["world"]
